### ISSUE TITLE
FV does not negotiate an acceptable OpenFlow version if a switch advertises >1.0

### ISSUE THREAD

**Issue by owens-bill** [opennetworkinglab/flowvisor#160]
Testing Flowvisor 0.8.17 with a Pica8 Pronto 3295 running latest firmware 1.6, which contains Open vSwitch 1.7.1+ and advertises OFP version 0x3. Flowvisor logs a few errors and then shuts down:

> Jan 23 10:29:28 wheel 1>Jan 23 10:29:28 flowvisor: INFO started flowvisor logger 
> Jan 23 10:29:28 wheel 1>Jan 23 10:29:28 flowvisor: ERROR none : log level enabled: CRIT 
> Jan 23 10:29:28 wheel 1>Jan 23 10:29:28 flowvisor: ERROR none : log level enabled: ALERT 
> Jan 23 10:29:28 wheel 1>Jan 23 10:29:28 flowvisor: WARN none : log level enabled: WARN 
> Jan 23 10:29:28 wheel 1>Jan 23 10:29:28 flowvisor: INFO none : log level enabled: INFO 
> Jan 23 10:29:28 wheel 1>Jan 23 10:29:28 flowvisor: INFO none : log level enabled: NOTE 
> Jan 23 10:29:28 wheel 1>Jan 23 10:29:28 flowvisor: INFO none : initializing poll loop 
> Jan 23 10:29:28 wheel 1>Jan 23 10:29:28 flowvisor: INFO none : JSON service disabled in config (Jetty webserver port == -1) 
> Jan 23 10:29:28 wheel 1>Jan 23 10:29:28 flowvisor: INFO OFSwitchAcceptor : Listenning on port 6633 
> Jan 23 10:29:28 wheel 1>Jan 23 10:29:28 flowvisor: INFO none : initializing FlowVisor UserAPI XMLRPC SSL WebServer on port 8080 
> Jan 23 10:29:28 wheel 1>Jan 23 10:29:28 flowvisor: INFO none : flowdb: Disabled 
> Jan 23 10:29:35 wheel 1>Jan 23 10:29:35 flowvisor: INFO OFSwitchAcceptor : got new connection: java.nio.channels.SocketChannel[connected local=/199.109.33.71:6633 remote=/x.x.x.10:49689] 
> Jan 23 10:29:35 wheel 1>Jan 23 10:29:35 flowvisor: ERROR OFSwitchAcceptor : STARVING: handling event took 35ms: org.flowvisor.events.FVIOEvent@109ce4a3 
> Jan 23 10:29:35 wheel 1>Jan 23 10:29:35 flowvisor: WARN classifier-unidentified:java.nio.channels.SocketChannel[connected local=/199.109.33.71:6633 remote=/x.x.x.10:49689] : Mismatched version from switch java.nio.channels.SocketChannel[connected local=/199.109.33.71:6633 remote=/x.x.x.10:49689] Got: 3 Wanted: 1 
> Jan 23 10:29:35 wheel 1>Jan 23 10:29:35 flowvisor: WARN classifier-unidentified:java.nio.channels.SocketChannel[connected local=/199.109.33.71:6633 remote=/x.x.x.10:49689] : tearing down 
> Jan 23 10:29:35 wheel 1>Jan 23 10:29:35 flowvisor: INFO classifier-dpid=00:00:04:7d:7b:6e:07:95 : identified switch as dpid=00:00:04:7d:7b:6e:07:95 on java.nio.channels.SocketChannel[closed] 
> Jan 23 10:29:35 wheel 1>Jan 23 10:29:35 flowvisor: WARN none : No match for: OFMatch[] 
> Jan 23 10:29:35 wheel 1>Jan 23 10:29:35 flowvisor: INFO none : Shutting down config database. 

Forcing the Pronto to advertise only 1.0 support allows it to connect. Looks as though FV needs to understand how to negotiate a version that it can handle.

**Comment by alshabib** [comment]
The problem here is that this switch is advertising OF version 1.3, which
flowvisor does not yet support. The error "Mismatched version from switch"
inducates this. Flowvisor only supports version 1.0.

## 

Ali Al-Shabibi (sent from handheld)

On 23 janv. 2013, at 07:35, owens-bill notifications@github.com wrote:

Testing Flowvisor 0.8.17 with a Pica8 Pronto 3295 running latest firmware
1.6, which contains Open vSwitch 1.7.1+ and advertises OFP version 0x3.
Flowvisor logs a few errors and then shuts down:

Jan 23 10:29:28 wheel 1>Jan 23 10:29:28 flowvisor: INFO started flowvisor
logger
Jan 23 10:29:28 wheel 1>Jan 23 10:29:28 flowvisor: ERROR none : log level
enabled: CRIT
Jan 23 10:29:28 wheel 1>Jan 23 10:29:28 flowvisor: ERROR none : log level
enabled: ALERT
Jan 23 10:29:28 wheel 1>Jan 23 10:29:28 flowvisor: WARN none : log level
enabled: WARN
Jan 23 10:29:28 wheel 1>Jan 23 10:29:28 flowvisor: INFO none : log level
enabled: INFO
Jan 23 10:29:28 wheel 1>Jan 23 10:29:28 flowvisor: INFO none : log level
enabled: NOTE
Jan 23 10:29:28 wheel 1>Jan 23 10:29:28 flowvisor: INFO none : initializing
poll loop
Jan 23 10:29:28 wheel 1>Jan 23 10:29:28 flowvisor: INFO none : JSON service
disabled in config (Jetty webserver port == -1)
Jan 23 10:29:28 wheel 1>Jan 23 10:29:28 flowvisor: INFO OFSwitchAcceptor :
Listenning on port 6633
Jan 23 10:29:28 wheel 1>Jan 23 10:29:28 flowvisor: INFO none : initializing
FlowVisor UserAPI XMLRPC SSL WebServer on port 8080
Jan 23 10:29:28 wheel 1>Jan 23 10:29:28 flowvisor: INFO none : flowdb:
Disabled
Jan 23 10:29:35 wheel 1>Jan 23 10:29:35 flowvisor: INFO OFSwitchAcceptor :
got new connection: java.nio.channels.SocketChannel[connected local=/
199.109.33.71:6633 remote=/x.x.x.10:49689]
Jan 23 10:29:35 wheel 1>Jan 23 10:29:35 flowvisor: ERROR OFSwitchAcceptor :
STARVING: handling event took 35ms:
org.flowvisor.events.FVIOEvent@109ce4ahttps://github.com/org.flowvisor.events.FVIOEvent/flowvisor/commit/109ce4a3
Jan 23 10:29:35 wheel 1>Jan 23 10:29:35 flowvisor: WARN
classifier-unidentified:java.nio.channels.SocketChannel[connected local=/
199.109.33.71:6633 remote=/x.x.x.10:49689] : Mismatched version from switch
java.nio.channels.SocketChannel[connected
local=/199.109.33.71:6633remote=/x.x.x.10:49689] Got: 3 Wanted: 1
Jan 23 10:29:35 wheel 1>Jan 23 10:29:35 flowvisor: WARN
classifier-unidentified:java.nio.channels.SocketChannel[connected local=/
199.109.33.71:6633 remote=/x.x.x.10:49689] : tearing down
Jan 23 10:29:35 wheel 1>Jan 23 10:29:35 flowvisor: INFO
classifier-dpid=00:00:04:7d:7b:6e:07:95 : identified switch as
dpid=00:00:04:7d:7b:6e:07:95 on java.nio.channels.SocketChannel[closed]
Jan 23 10:29:35 wheel 1>Jan 23 10:29:35 flowvisor: WARN none : No match
for: OFMatch[]
Jan 23 10:29:35 wheel 1>Jan 23 10:29:35 flowvisor: INFO none : Shutting
down config database.

Forcing the Pronto to advertise only 1.0 support allows it to connect.
Looks as though FV needs to understand how to negotiate a version that it
can handle.

—
Reply to this email directly or view it on
GitHubhttps://github.com/OPENNETWORKINGLAB/flowvisor/issues/160.

**Comment by nbastin** [comment]
Advertising 1.3 isn't wrong, there's a negotiation stage that allows for backoff to a shared-common-version, the question is who is doing it wrong here.

**Comment by alshabib** [comment]
Ahh right, I didn't get that from the bug report. In this case, this is an actual bug that needs addressing.

**Comment by jbsbbn** [comment]
Also, whether or not negotiation works, it certainly shouldn't crash FV.

**Comment by alshabib** [comment]
I don't see a crash, FV just teardown the connection to that switch because there is no acceptable version. This seems reasonable to me.

**Comment by nbastin** [comment]
What does "Jan 23 10:29:35 wheel 1>Jan 23 10:29:35 flowvisor: INFO none : Shutting down config database." mean, I guess?  (Maybe that isn't a crash, but it doesn't seem good)

**Comment by alshabib** [comment]
That's just a message that indicates that the db closed cleanly when FV exists, that's not a crash.

**Comment by jbsbbn** [comment]
Just to clarify, we think that FV really is shutting down when the switch connects; whether that's a "crash" or  "clean shutdown" doesn't matter so much, it certainly shouldn't end up in a not-running state.

**Comment by alshabib** [comment]
Agreed, this is a legitimate bug.

**Comment by alshabib** [comment]
fixed in nightly.

**Comment by vishleshpatel** [comment]
Do flowvisor support OpenFlow 1.3 now?

**Comment by alshabib** [comment]
Sorry FV does not support 1.3. 

## 

Ali Al-Shabibi (sent from handheld)

**Comment by vishleshpatel** [comment]
hi alshabib,

Thanks a lot for reply. Which latest openflow version flowvisor supports? 

I am new in flowvisor. Can you help me with the following error:

Flowvisor successfully runs and connects to ovs switches. But i am unable to create slice here

sudo fvctl -f /dev/null add-slice slice1 tcp:localhost:6634 vishlesh.patel12@gmail.com
[sudo] password for vishlesh:
Slice password:
Internal Error -> add-slice: Unable to fetch slice list : Unknown slice slice1

**Comment by Skullbash27** [comment]
Hi alshabib, I know as of now Flowvisor does not support OpenFlow 1.3. Could you let me know if support for OpenFlow 1.3 is planned for Flowvisor in the future and by when it can be available for implementation? Also, if not, is there any other Network Slicing solution like Flowvisor which has full support for OpenFlow 1.3? (P.S: I already know of OpenVirteX, but that does not have Java 1.8 support)

**Comment by leenheer** [comment]
Austin,

your best bet will be to reach out to the ONOS virtualization brigade.

https://wiki.onosproject.org/display/ONOS/Virtualization+brigade <https://wiki.onosproject.org/display/ONOS/Virtualization+brigade>


Regards,

marc

**Comment by Skullbash27** [comment]
Hi leenheer, Thank you for the swift response. I was just reading through the pages there. I notice that this tool seems to be ONOS specific (if I am not wrong, as the Brigade says its to be put as a feature for upcoming versions of the ONOS SDN controller). I am using the FloodLight controller as the SDN controller for my research, is there any tool that could be used with FloodLight?

**Comment by leenheer** [comment]
I think they will allow external controllers to be used, but you should really ask them.


marc

**Comment by Skullbash27** [comment]
Hi leenheer, As suggested, I shall check with the ONOS team. Thank you.
