### ISSUE TITLE
Using "fvctl add-flowspace" doesn't seem to work

### ISSUE THREAD

**Issue by lionelli1** [opennetworkinglab/flowvisor#188]
I created a new slice, and decided to add a new flowspace.

I did the following to add a new flowspace: fvctl add-flowspace myflowspace all 32000 any "Slice:firstSlice=4". I got "Flowspace myflowspace has been created." as response

However when I checked whether the flowspace exists with: fvctl list-flowspace, it showed nothing.

Is there an alternative way to create a flowspace?

**Comment by alshabib** [comment]
I am or quite sure why this is happening. Is your slice active?

In the meantime, you can revert to the xmlrpc interface. The process to do
this is described on the wiki.

## 

Ali Al-Shabibi

On Mar 26, 2013, at 1:18, Lionel Li notifications@github.com wrote:

I created a new slice, and decided to add a new flowspace.

I did the following to add a new flowspace: fvctl add-flowspace myflowspace
all 32000 any "Slice:firstSlice=4". I got "Flowspace myflowspace has been
created." as response

However when I checked whether the flowspace exists with: fvctl
list-flowspace, it showed nothing.

Is there an alternative way to create a flowspace?

—
Reply to this email directly or view it on
GitHubhttps://github.com/OPENNETWORKINGLAB/flowvisor/issues/188
.

**Comment by lionelli1** [comment]
Yes, I have verified that the flowvisor instance and the target were active. The XMLRPC worked for me.

By the way, is there any good tutorials that you would recommend on how to effectively create the different flowspaces for different needs? I'm new to OpenFlow and FlowVisor and I would like to better grasp how to slice a network. Thanks!

**Comment by alshabib** [comment]
The issue is that you have specified the slice name as 'Slice:firstSlice' rather than just 'firstSlice'. So the command should be:

fvctl add-flowspace myflowspace all 32000 any firstSlice=4

You can try the tutorial at https://openflow.stanford.edu/display/ONL/Flowvisor and download the VM from:

https://s3.amazonaws.com/onlab-downloads/ETH+Tutorial.ova 

The tutorial isn't very polished, any contribution is welcome. In the future, please ask question on the openflow-discuss mailing list.
