### ISSUE TITLE
fvctl set-config should let you set all configurable variables

### ISSUE THREAD

**Issue by jbsbbn** [opennetworkinglab/flowvisor#213]
Similar to https://github.com/OPENNETWORKINGLAB/flowvisor/issues/212, fvctl-setconfig should allow you to set every configurable variable, i.e. everything in

```
{
  "api_webserver_port": 8080,
  "db_version": 2,
  "host": "localhost",
  "log_ident": "flowvisor",
  "checkpointing": false,
  "listen_port": 6633,
  "logging": "NOTE",
  "run_topology_server": false,
  "log_facility": "LOG_LOCAL7",
  "version": "flowvisor-1.0.1",
  "config_name": "default",
  "api_jetty_webserver_port": 38274,
  "default_flood_perm": "fvadmin",
  "track_flows": false,
  "stats_desc_hack": false
}
```

There may be some things in the latter that you don't want people to be changing, which is fine, but anything that an admin can safely configure should be settable with set-config.

**Comment by mssumanth** [comment]
Hi Josh,

Many of these variables are just there for historical reasons and can be safely ignored like 'checkpointing', etc
Some of them cannot be(or atleast doesn't make sense setting) set or changed like: 'version' ; ''db_version",etc
Some of them are hard to change during run time.
Do you really want these variables(or some of them atleast) to be allowed to be set during run time ?

I will document what these variables are in one of the other issues for you to check if it really makes sense setting any of them! 

Thanks
Sumanth

**Comment by jbsbbn** [comment]
Yeah, I think just documenting what everything else, and explaining why it doesn't make sense to set the things that it doesn't make sense to set (for whatever reason) would be fine.

**Comment by mssumanth** [comment]
As of now, apart from the configuration parameters which can be set like:
stats_desc_hack, track_flows, default_flood_perm, run_topology_server, 
setting of none of the other configuration parameters makes sense.

api_webserver_port: The port number at which FlowVisor listens to the xml api requests.
api_jetty_webserver_port: The port number at which FlowVisor listens to the JSON api requests.
listen_port: The port on which FlowVisor listens from the switch.
host: Hostname on which FlowVisor is running.
Changing any of the above ports dynamically during FV running can lead to trouble.
log_ident: This is the identifier which should appear in every trace file- the name (say 'flowvisor') which should come after the date, but due to some log4j issue is not working presently. (But in any case we are planning to shift from log4j to slf4j for logging).
checkpointing: Regenerates the config.xml file. It was relevant earlier when there was no FlowVisor DB.
logging: It tells about the log level enabled in FlowVisor.The setting of this attribute can be done via fvlog.config 
config_name: This parameter was present to switch between configuration files. Has no effect as of now as the functionality for changing configuration files dynamically is not implemented.
version: Doesn't make sense to change the version number of FV.
db_version: Database Version. Similar reason as above.

More info on all the config parameters can be found here:
https://github.com/OPENNETWORKINGLAB/flowvisor/wiki/Configuration-Parameters
