### ISSUE TITLE
Clients can't detect failures that happen after a request is accepted

### ISSUE THREAD

**Issue by jbsbbn** [opennetworkinglab/flowvisor#217]
If a request isn't malformed, and is thus accepted by FlowVisor, it reports success to the client, and then goes to work on the request in the background. If the request later fails for some reason, the client doesn't have a way to find that out, or find out what actually happened, or to learn why. (e.g. by polling with a token that FV gave it, corresponding to the request)

**Comment by alshabib** [comment]
fixed in 1.0.3 and in commit 61c6dbbb3d7957a6804ef45d98f6a35ae2761e40

New API has been added to check the insertion status of a big add-flowspace command. add-flowspace now returns a request id, that can be passwd to list-fs-status. list-fs-status return either [SUCCESS, PENDING, UNKNOWN, error_msg]. SUCCESS indicates successful insertion, PENDING indicates a request that is still in process, UNKNOWN indicates the id passed is not known to the system, and error_msg is the failure condition for this id.
