### ISSUE TITLE
Flowvisor should be able to ask the flow table from the switch

### ISSUE THREAD

**Issue by billsnow** [opennetworkinglab/flowvisor#59]
Status: Open
Project:    Flowvisor
Component/s:    Core
Affects Version/s:  0.8.1
Fix Version/s:   None

Type:    New Feature    Priority:    Major
Reporter:   Niky Riga   Assignee:   Nick Bastin
Resolution:  Unresolved Votes:   0
Labels:  needinfo
Remaining Estimate:  Not Specified
Time Spent:  Not Specified
Original Estimate:   Not Specified

 Description  
Add a fvctl command that will allow the user to query a dpid about its flow table.

 Comments  
Comment by Ali Al-Shabibi [ 06/Feb/12 ]
I am not quite sure what the intention is here. Should the fvctl command return the actual flowtable on the switch or the flowtable for each slice in fv?
The first case is relatively easy to implement, but the second requires flow tracking to be turned on.

Original issue: https://openflow.stanford.edu/bugs/browse/FLOWVISOR-142

**Comment by chaos-bbn** [comment]
Ali: Niky and i discussed this ticket, and we think that, while there might be an eventual use case for per-slice data, just getting the data at all will do what we most want here, which is to have the flows available for debugging and/or error-detection.  Since it sounds like per-switch is easier to implement than per-slice, and gets us most of the value we want, let's define this ticket as requesting that fvctl provide the per-switch flowtable.

**Comment by alshabib** [comment]
Actually we are thinking of delivering this on a per slice per switch
basis. The per slice part would probably be optional.

On 17 avr. 2013, at 14:15, chaos-bbn notifications@github.com wrote:

Ali: Niky and i discussed this ticket, and we think that, while there might
be an eventual use case for per-slice data, just getting the data at all
will do what we most want here, which is to have the flows available for
debugging and/or error-detection. Since it sounds like per-switch is easier
to implement than per-slice, and gets us most of the value we want, let's
define this ticket as requesting that fvctl provide the per-switch
flowtable.

—
Reply to this email directly or view it on
GitHubhttps://github.com/OPENNETWORKINGLAB/flowvisor/issues/59#issuecomment-16536232
.

**Comment by chaos-bbn** [comment]
Sounds good.  I think it's better for me if per-slice is optional, since, if i'm getting everything on a switch, then i'm guessing it will be cheaper, performance-wise, to get it all at once in one operation than to poll repeatedly.

**Comment by mssumanth** [comment]
FV now supports getting flowtable info from a particular switch. 
A callback is established to the given method and url once the statsReply is available from the desired switch.
It is supported only on JSON RPC as XML RPC is deprecated.
Committed in: 6685bf82d59abf09fa1b80f23509ac8d5d7849ed

**Comment by mssumanth** [comment]
Fixed in 1.2.0
