### ISSUE TITLE
changeFlowSpace is very slow

### ISSUE THREAD

**Issue by nbastin** [opennetworkinglab/flowvisor#87]
The changeFlowSpace API has gotten slower (it was never great) - we need to make flowspace changes a lot and the time it takes affects convergence when new VMs are brought up and have ports that need to be added to different slices, etc.

**Comment by alshabib** [comment]
ChangeFlowSpace command taking too long to execute. It is due FV add the rules to the DB and not updating the state of the various slicers and classifiers. 

So the issue is now if whether we want the changeFlowSpace command to return immediately and therefore it will not return the newly created id. Which in turn means that a user will need to list the flowspace in order  to get the ids of the flowspace entries.

I am not quite sure whether it is better to have changeFlowSpace return new ids or require users to get the flowspace to find the ids they need. 

Anyone who cares, please comment

**Comment by jbsbbn** [comment]
I haven't thought about this too hard, but when does the user need to know the flowspace ID? As a human running fvctl, I don't know that I ever have.

A program might, I suppose. Nick, does FOAM?

**Comment by alshabib** [comment]
The ids are useful to allow to delete the flowspace entries later on.
Whether this is useful at the time of creation is up for debate.

## 

Ali Al-Shabibi (sent from handheld)

On 10 janv. 2013, at 20:06, Josh Smift notifications@github.com wrote:

I haven't thought about this too hard, but when does the user need to know
the flowspace ID? As a human running fvctl, I don't know that I ever have.

A program might, I suppose. Nick, does FOAM?

—
Reply to this email directly or view it on
GitHubhttps://github.com/OPENNETWORKINGLAB/flowvisor/issues/87#issuecomment-12113162.

**Comment by jbsbbn** [comment]
Do the rule IDs ever change, e.g. if you dump and restore the DB? I think I have seen them change, in which case you really need to look them up immediately before you do anything that uses them (e.g. you can't just cache them at create time and then rely on them being the same later).

**Comment by alshabib** [comment]
Rule ids may change if you dump the config and reload it. This is because
when you reload the db from a config file, fv resets all the database ids
to avoid potential id collisions.

This probably means that we don't care about ids at creation time.

## 

Ali Al-Shabibi (sent from handheld)

On 10 janv. 2013, at 20:20, Josh Smift notifications@github.com wrote:

Do the rule IDs ever change, e.g. if you dump and restore the DB? I think I
have seen them change, in which case you really need to look them up
immediately before you do anything that uses them (e.g. you can't just
cache them at create time and then rely on them being the same later).

—
Reply to this email directly or view it on
GitHubhttps://github.com/OPENNETWORKINGLAB/flowvisor/issues/87#issuecomment-12113835.

**Comment by nbastin** [comment]
We do not (cannot) care about rule IDs, because they change too much.

**Comment by alshabib** [comment]
Is this a subtle way of saying that they should never change? ;)

## 

Ali Al-Shabibi (sent from handheld)

On 10 janv. 2013, at 22:02, Nick Bastin notifications@github.com wrote:

We do not (cannot) care about rule IDs, because they change too much.

—
Reply to this email directly or view it on
GitHubhttps://github.com/OPENNETWORKINGLAB/flowvisor/issues/87#issuecomment-12118461.

**Comment by nbastin** [comment]
Honestly I mostly don't care, but there's definitely an argument to be made there.  Right now if you want to delete just one flowspace entry (or at least a subset of a slice), you have to query the entire flowspace (which might be hundreds of thousands of entries), and then hope nothing happens in between parsing that output and deleting the records.

I think what I really want is for flowspace IDs to be slice-local (e.g. each slice will have ID 1...N) and deterministic.  This is really because I _don't_ like it that the entire flowspace is returned to me when I add it (in the new JSON API) just so I can have the flowspace IDs - this seems ridiculously expensive for large requests.  However, I haven't given this a lot of thought and maybe it doesn't really work.  Certainly anything done here needs to be thought about and designed with multiple use cases in mind.

**Comment by alshabib** [comment]
So for the record, the flowspace is no longer returned when added (I
changed it recently). In fairness, flowspace ids don't change during fv
runtime, they _may_ only change if you reload and rebuild the db from the
config file, and even then under certain conditions would that be true. If
fv restarts, then your client needs to be restarted as well assuming you
are using a persistent connection to fv.

Also this may introduce the need to give flowspace entries a user-defined
name to allow users to delete flowspace either by id or name. Slice local
ids make sense, it would require some more thought and redesign.

## 

Ali Al-Shabibi (sent from handheld)

On 10 janv. 2013, at 22:13, Nick Bastin notifications@github.com wrote:

Honestly I mostly don't care, but there's definitely an argument to be made
there. Right now if you want to delete just one flowspace entry (or at
least a subset of a slice), you have to query the entire flowspace (which
might be hundreds of thousands of entries), and then hope nothing happens
in between parsing that output and deleting the records.

I think what I really want is for flowspace IDs to be slice-local (e.g.
each slice will have ID 1...N) and deterministic. This is really because I *
don't\* like it that the entire flowspace is returned to me when I add it
(in the new JSON API) just so I can have the flowspace IDs - this seems
ridiculously expensive for large requests. However, I haven't given this a
lot of thought and maybe it doesn't really work. Certainly anything done
here needs to be thought about and designed with multiple use cases in mind.

—
Reply to this email directly or view it on
GitHubhttps://github.com/OPENNETWORKINGLAB/flowvisor/issues/87#issuecomment-12118970.

**Comment by nbastin** [comment]
There's no way to make a persistent connection to the FlowVisor, so this is a somewhat academic discussion (you can't hold the connection open while idle for very long before the remote end closes it - as it should - it's possible that 0.10 changes this behaviour, but I'm not sure why that would be desirable).  Even if you were using this mystery persistent connection, one would hope you did not have to restart your client for it to start another connection if it got disconnected.

If you download 20k FS entries, it's not unreasonable to assume that someone has restarted FlowVisor between when you asked for them and when you had sufficiently parsed them in order to make the next call.

**Comment by alshabib** [comment]
0.10 changes no API behaviour what so ever.

My original question was, should we return newly created ids. If yes, then
it would make sense that these ids persist. If not then it really doesn't
matter.

Also, does this introduce the need to allow users to name flowspace entries
so as to refer to them more easily.

## 

Ali Al-Shabibi (sent from handheld)

On 10 janv. 2013, at 22:59, Nick Bastin notifications@github.com wrote:

There's no way to make a persistent connection to the FlowVisor, so this is
a somewhat academic discussion (you can't hold the connection open while
idle for very long before the remote end closes it - as it should - it's
possible that 0.10 changes this behaviour, but I'm not sure why that would
be desirable). Even if you were using this mystery persistent connection,
one would hope you did not have to restart your client for it to start
another connection if it got disconnected.

If you download 20k FS entries, it's not unreasonable to assume that
someone has restarted FlowVisor between when you asked for them and when
you had sufficiently parsed them in order to make the next call.

—
Reply to this email directly or view it on
GitHubhttps://github.com/OPENNETWORKINGLAB/flowvisor/issues/87#issuecomment-12121011.

**Comment by nbastin** [comment]
As long as we think it is valuable to address an individual rule, then it needs to have some kind of identifier.  Historically that identifier has only been valid for the current instance of FlowVisor, and that limited the usefulness of this identifier (but functional in some situations).  "All" problems related to these identifies would be addressed if they were persistent - whether that means they're slice-scoped, or user-defined, or FV-provided but immutable probably doesn't really matter.
